version: '3.8'
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
      - /app/build
    env_file:
      - .env
    environment:
      - ORIGIN_URL=http://localhost:5173
    network_mode: "host"

  code-runner:
    build: ./code-runner
    container_name: code-runner_c
    volumes:
      - ./code-runner:/app
      - /app/node_modules
      - /app/runtime
    env_file:
      - .env
    network_mode: "host"

  redis:
    image: redis:7.0.12
    container_name: redis_c
    ports:
      - "6379:6379"
