name: Keep SML Playground Alive
on:
  schedule:
    - cron: "*/14 * * * *"  # Run every 14 minutes

jobs:
  execute_code:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST Request to SML Playground
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"code": "print(1);"}' https://sml-playground-api.onrender.com/execute
